# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/zixiong/firewall

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/zixiong/firewall

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zixiong/firewall/CMakeFiles /Users/zixiong/firewall/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zixiong/firewall/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named firewall

# Build rule for target.
firewall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 firewall
.PHONY : firewall

# fast build rule for target.
firewall/fast:
	$(MAKE) -f CMakeFiles/firewall.dir/build.make CMakeFiles/firewall.dir/build
.PHONY : firewall/fast

Utils/crc32.o: Utils/crc32.c.o

.PHONY : Utils/crc32.o

# target to build an object file
Utils/crc32.c.o:
	$(MAKE) -f CMakeFiles/firewall.dir/build.make CMakeFiles/firewall.dir/Utils/crc32.c.o
.PHONY : Utils/crc32.c.o

Utils/crc32.i: Utils/crc32.c.i

.PHONY : Utils/crc32.i

# target to preprocess a source file
Utils/crc32.c.i:
	$(MAKE) -f CMakeFiles/firewall.dir/build.make CMakeFiles/firewall.dir/Utils/crc32.c.i
.PHONY : Utils/crc32.c.i

Utils/crc32.s: Utils/crc32.c.s

.PHONY : Utils/crc32.s

# target to generate assembly for a file
Utils/crc32.c.s:
	$(MAKE) -f CMakeFiles/firewall.dir/build.make CMakeFiles/firewall.dir/Utils/crc32.c.s
.PHONY : Utils/crc32.c.s

Utils/fingerprint.o: Utils/fingerprint.c.o

.PHONY : Utils/fingerprint.o

# target to build an object file
Utils/fingerprint.c.o:
	$(MAKE) -f CMakeFiles/firewall.dir/build.make CMakeFiles/firewall.dir/Utils/fingerprint.c.o
.PHONY : Utils/fingerprint.c.o

Utils/fingerprint.i: Utils/fingerprint.c.i

.PHONY : Utils/fingerprint.i

# target to preprocess a source file
Utils/fingerprint.c.i:
	$(MAKE) -f CMakeFiles/firewall.dir/build.make CMakeFiles/firewall.dir/Utils/fingerprint.c.i
.PHONY : Utils/fingerprint.c.i

Utils/fingerprint.s: Utils/fingerprint.c.s

.PHONY : Utils/fingerprint.s

# target to generate assembly for a file
Utils/fingerprint.c.s:
	$(MAKE) -f CMakeFiles/firewall.dir/build.make CMakeFiles/firewall.dir/Utils/fingerprint.c.s
.PHONY : Utils/fingerprint.c.s

Utils/generators.o: Utils/generators.c.o

.PHONY : Utils/generators.o

# target to build an object file
Utils/generators.c.o:
	$(MAKE) -f CMakeFiles/firewall.dir/build.make CMakeFiles/firewall.dir/Utils/generators.c.o
.PHONY : Utils/generators.c.o

Utils/generators.i: Utils/generators.c.i

.PHONY : Utils/generators.i

# target to preprocess a source file
Utils/generators.c.i:
	$(MAKE) -f CMakeFiles/firewall.dir/build.make CMakeFiles/firewall.dir/Utils/generators.c.i
.PHONY : Utils/generators.c.i

Utils/generators.s: Utils/generators.c.s

.PHONY : Utils/generators.s

# target to generate assembly for a file
Utils/generators.c.s:
	$(MAKE) -f CMakeFiles/firewall.dir/build.make CMakeFiles/firewall.dir/Utils/generators.c.s
.PHONY : Utils/generators.c.s

Utils/hashgenerator.o: Utils/hashgenerator.c.o

.PHONY : Utils/hashgenerator.o

# target to build an object file
Utils/hashgenerator.c.o:
	$(MAKE) -f CMakeFiles/firewall.dir/build.make CMakeFiles/firewall.dir/Utils/hashgenerator.c.o
.PHONY : Utils/hashgenerator.c.o

Utils/hashgenerator.i: Utils/hashgenerator.c.i

.PHONY : Utils/hashgenerator.i

# target to preprocess a source file
Utils/hashgenerator.c.i:
	$(MAKE) -f CMakeFiles/firewall.dir/build.make CMakeFiles/firewall.dir/Utils/hashgenerator.c.i
.PHONY : Utils/hashgenerator.c.i

Utils/hashgenerator.s: Utils/hashgenerator.c.s

.PHONY : Utils/hashgenerator.s

# target to generate assembly for a file
Utils/hashgenerator.c.s:
	$(MAKE) -f CMakeFiles/firewall.dir/build.make CMakeFiles/firewall.dir/Utils/hashgenerator.c.s
.PHONY : Utils/hashgenerator.c.s

Utils/hashpackettest.o: Utils/hashpackettest.c.o

.PHONY : Utils/hashpackettest.o

# target to build an object file
Utils/hashpackettest.c.o:
	$(MAKE) -f CMakeFiles/firewall.dir/build.make CMakeFiles/firewall.dir/Utils/hashpackettest.c.o
.PHONY : Utils/hashpackettest.c.o

Utils/hashpackettest.i: Utils/hashpackettest.c.i

.PHONY : Utils/hashpackettest.i

# target to preprocess a source file
Utils/hashpackettest.c.i:
	$(MAKE) -f CMakeFiles/firewall.dir/build.make CMakeFiles/firewall.dir/Utils/hashpackettest.c.i
.PHONY : Utils/hashpackettest.c.i

Utils/hashpackettest.s: Utils/hashpackettest.c.s

.PHONY : Utils/hashpackettest.s

# target to generate assembly for a file
Utils/hashpackettest.c.s:
	$(MAKE) -f CMakeFiles/firewall.dir/build.make CMakeFiles/firewall.dir/Utils/hashpackettest.c.s
.PHONY : Utils/hashpackettest.c.s

Utils/hashpacketworker.o: Utils/hashpacketworker.c.o

.PHONY : Utils/hashpacketworker.o

# target to build an object file
Utils/hashpacketworker.c.o:
	$(MAKE) -f CMakeFiles/firewall.dir/build.make CMakeFiles/firewall.dir/Utils/hashpacketworker.c.o
.PHONY : Utils/hashpacketworker.c.o

Utils/hashpacketworker.i: Utils/hashpacketworker.c.i

.PHONY : Utils/hashpacketworker.i

# target to preprocess a source file
Utils/hashpacketworker.c.i:
	$(MAKE) -f CMakeFiles/firewall.dir/build.make CMakeFiles/firewall.dir/Utils/hashpacketworker.c.i
.PHONY : Utils/hashpacketworker.c.i

Utils/hashpacketworker.s: Utils/hashpacketworker.c.s

.PHONY : Utils/hashpacketworker.s

# target to generate assembly for a file
Utils/hashpacketworker.c.s:
	$(MAKE) -f CMakeFiles/firewall.dir/build.make CMakeFiles/firewall.dir/Utils/hashpacketworker.c.s
.PHONY : Utils/hashpacketworker.c.s

Utils/hashtable.o: Utils/hashtable.c.o

.PHONY : Utils/hashtable.o

# target to build an object file
Utils/hashtable.c.o:
	$(MAKE) -f CMakeFiles/firewall.dir/build.make CMakeFiles/firewall.dir/Utils/hashtable.c.o
.PHONY : Utils/hashtable.c.o

Utils/hashtable.i: Utils/hashtable.c.i

.PHONY : Utils/hashtable.i

# target to preprocess a source file
Utils/hashtable.c.i:
	$(MAKE) -f CMakeFiles/firewall.dir/build.make CMakeFiles/firewall.dir/Utils/hashtable.c.i
.PHONY : Utils/hashtable.c.i

Utils/hashtable.s: Utils/hashtable.c.s

.PHONY : Utils/hashtable.s

# target to generate assembly for a file
Utils/hashtable.c.s:
	$(MAKE) -f CMakeFiles/firewall.dir/build.make CMakeFiles/firewall.dir/Utils/hashtable.c.s
.PHONY : Utils/hashtable.c.s

Utils/packetsource.o: Utils/packetsource.c.o

.PHONY : Utils/packetsource.o

# target to build an object file
Utils/packetsource.c.o:
	$(MAKE) -f CMakeFiles/firewall.dir/build.make CMakeFiles/firewall.dir/Utils/packetsource.c.o
.PHONY : Utils/packetsource.c.o

Utils/packetsource.i: Utils/packetsource.c.i

.PHONY : Utils/packetsource.i

# target to preprocess a source file
Utils/packetsource.c.i:
	$(MAKE) -f CMakeFiles/firewall.dir/build.make CMakeFiles/firewall.dir/Utils/packetsource.c.i
.PHONY : Utils/packetsource.c.i

Utils/packetsource.s: Utils/packetsource.c.s

.PHONY : Utils/packetsource.s

# target to generate assembly for a file
Utils/packetsource.c.s:
	$(MAKE) -f CMakeFiles/firewall.dir/build.make CMakeFiles/firewall.dir/Utils/packetsource.c.s
.PHONY : Utils/packetsource.c.s

Utils/paddedprim.o: Utils/paddedprim.c.o

.PHONY : Utils/paddedprim.o

# target to build an object file
Utils/paddedprim.c.o:
	$(MAKE) -f CMakeFiles/firewall.dir/build.make CMakeFiles/firewall.dir/Utils/paddedprim.c.o
.PHONY : Utils/paddedprim.c.o

Utils/paddedprim.i: Utils/paddedprim.c.i

.PHONY : Utils/paddedprim.i

# target to preprocess a source file
Utils/paddedprim.c.i:
	$(MAKE) -f CMakeFiles/firewall.dir/build.make CMakeFiles/firewall.dir/Utils/paddedprim.c.i
.PHONY : Utils/paddedprim.c.i

Utils/paddedprim.s: Utils/paddedprim.c.s

.PHONY : Utils/paddedprim.s

# target to generate assembly for a file
Utils/paddedprim.c.s:
	$(MAKE) -f CMakeFiles/firewall.dir/build.make CMakeFiles/firewall.dir/Utils/paddedprim.c.s
.PHONY : Utils/paddedprim.c.s

Utils/seriallist.o: Utils/seriallist.c.o

.PHONY : Utils/seriallist.o

# target to build an object file
Utils/seriallist.c.o:
	$(MAKE) -f CMakeFiles/firewall.dir/build.make CMakeFiles/firewall.dir/Utils/seriallist.c.o
.PHONY : Utils/seriallist.c.o

Utils/seriallist.i: Utils/seriallist.c.i

.PHONY : Utils/seriallist.i

# target to preprocess a source file
Utils/seriallist.c.i:
	$(MAKE) -f CMakeFiles/firewall.dir/build.make CMakeFiles/firewall.dir/Utils/seriallist.c.i
.PHONY : Utils/seriallist.c.i

Utils/seriallist.s: Utils/seriallist.c.s

.PHONY : Utils/seriallist.s

# target to generate assembly for a file
Utils/seriallist.c.s:
	$(MAKE) -f CMakeFiles/firewall.dir/build.make CMakeFiles/firewall.dir/Utils/seriallist.c.s
.PHONY : Utils/seriallist.c.s

Utils/statistics.o: Utils/statistics.c.o

.PHONY : Utils/statistics.o

# target to build an object file
Utils/statistics.c.o:
	$(MAKE) -f CMakeFiles/firewall.dir/build.make CMakeFiles/firewall.dir/Utils/statistics.c.o
.PHONY : Utils/statistics.c.o

Utils/statistics.i: Utils/statistics.c.i

.PHONY : Utils/statistics.i

# target to preprocess a source file
Utils/statistics.c.i:
	$(MAKE) -f CMakeFiles/firewall.dir/build.make CMakeFiles/firewall.dir/Utils/statistics.c.i
.PHONY : Utils/statistics.c.i

Utils/statistics.s: Utils/statistics.c.s

.PHONY : Utils/statistics.s

# target to generate assembly for a file
Utils/statistics.c.s:
	$(MAKE) -f CMakeFiles/firewall.dir/build.make CMakeFiles/firewall.dir/Utils/statistics.c.s
.PHONY : Utils/statistics.c.s

Utils/stopwatch.o: Utils/stopwatch.c.o

.PHONY : Utils/stopwatch.o

# target to build an object file
Utils/stopwatch.c.o:
	$(MAKE) -f CMakeFiles/firewall.dir/build.make CMakeFiles/firewall.dir/Utils/stopwatch.c.o
.PHONY : Utils/stopwatch.c.o

Utils/stopwatch.i: Utils/stopwatch.c.i

.PHONY : Utils/stopwatch.i

# target to preprocess a source file
Utils/stopwatch.c.i:
	$(MAKE) -f CMakeFiles/firewall.dir/build.make CMakeFiles/firewall.dir/Utils/stopwatch.c.i
.PHONY : Utils/stopwatch.c.i

Utils/stopwatch.s: Utils/stopwatch.c.s

.PHONY : Utils/stopwatch.s

# target to generate assembly for a file
Utils/stopwatch.c.s:
	$(MAKE) -f CMakeFiles/firewall.dir/build.make CMakeFiles/firewall.dir/Utils/stopwatch.c.s
.PHONY : Utils/stopwatch.c.s

firewall.o: firewall.c.o

.PHONY : firewall.o

# target to build an object file
firewall.c.o:
	$(MAKE) -f CMakeFiles/firewall.dir/build.make CMakeFiles/firewall.dir/firewall.c.o
.PHONY : firewall.c.o

firewall.i: firewall.c.i

.PHONY : firewall.i

# target to preprocess a source file
firewall.c.i:
	$(MAKE) -f CMakeFiles/firewall.dir/build.make CMakeFiles/firewall.dir/firewall.c.i
.PHONY : firewall.c.i

firewall.s: firewall.c.s

.PHONY : firewall.s

# target to generate assembly for a file
firewall.c.s:
	$(MAKE) -f CMakeFiles/firewall.dir/build.make CMakeFiles/firewall.dir/firewall.c.s
.PHONY : firewall.c.s

myqueue.o: myqueue.c.o

.PHONY : myqueue.o

# target to build an object file
myqueue.c.o:
	$(MAKE) -f CMakeFiles/firewall.dir/build.make CMakeFiles/firewall.dir/myqueue.c.o
.PHONY : myqueue.c.o

myqueue.i: myqueue.c.i

.PHONY : myqueue.i

# target to preprocess a source file
myqueue.c.i:
	$(MAKE) -f CMakeFiles/firewall.dir/build.make CMakeFiles/firewall.dir/myqueue.c.i
.PHONY : myqueue.c.i

myqueue.s: myqueue.c.s

.PHONY : myqueue.s

# target to generate assembly for a file
myqueue.c.s:
	$(MAKE) -f CMakeFiles/firewall.dir/build.make CMakeFiles/firewall.dir/myqueue.c.s
.PHONY : myqueue.c.s

tests.o: tests.c.o

.PHONY : tests.o

# target to build an object file
tests.c.o:
	$(MAKE) -f CMakeFiles/firewall.dir/build.make CMakeFiles/firewall.dir/tests.c.o
.PHONY : tests.c.o

tests.i: tests.c.i

.PHONY : tests.i

# target to preprocess a source file
tests.c.i:
	$(MAKE) -f CMakeFiles/firewall.dir/build.make CMakeFiles/firewall.dir/tests.c.i
.PHONY : tests.c.i

tests.s: tests.c.s

.PHONY : tests.s

# target to generate assembly for a file
tests.c.s:
	$(MAKE) -f CMakeFiles/firewall.dir/build.make CMakeFiles/firewall.dir/tests.c.s
.PHONY : tests.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... firewall"
	@echo "... Utils/crc32.o"
	@echo "... Utils/crc32.i"
	@echo "... Utils/crc32.s"
	@echo "... Utils/fingerprint.o"
	@echo "... Utils/fingerprint.i"
	@echo "... Utils/fingerprint.s"
	@echo "... Utils/generators.o"
	@echo "... Utils/generators.i"
	@echo "... Utils/generators.s"
	@echo "... Utils/hashgenerator.o"
	@echo "... Utils/hashgenerator.i"
	@echo "... Utils/hashgenerator.s"
	@echo "... Utils/hashpackettest.o"
	@echo "... Utils/hashpackettest.i"
	@echo "... Utils/hashpackettest.s"
	@echo "... Utils/hashpacketworker.o"
	@echo "... Utils/hashpacketworker.i"
	@echo "... Utils/hashpacketworker.s"
	@echo "... Utils/hashtable.o"
	@echo "... Utils/hashtable.i"
	@echo "... Utils/hashtable.s"
	@echo "... Utils/packetsource.o"
	@echo "... Utils/packetsource.i"
	@echo "... Utils/packetsource.s"
	@echo "... Utils/paddedprim.o"
	@echo "... Utils/paddedprim.i"
	@echo "... Utils/paddedprim.s"
	@echo "... Utils/seriallist.o"
	@echo "... Utils/seriallist.i"
	@echo "... Utils/seriallist.s"
	@echo "... Utils/statistics.o"
	@echo "... Utils/statistics.i"
	@echo "... Utils/statistics.s"
	@echo "... Utils/stopwatch.o"
	@echo "... Utils/stopwatch.i"
	@echo "... Utils/stopwatch.s"
	@echo "... firewall.o"
	@echo "... firewall.i"
	@echo "... firewall.s"
	@echo "... myqueue.o"
	@echo "... myqueue.i"
	@echo "... myqueue.s"
	@echo "... tests.o"
	@echo "... tests.i"
	@echo "... tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

